import Head from 'next/head'

export default function Home() {
  return (
    <div className="w-[1200px] max-w-full mx-auto">
      <Head>
        <title>Best Before</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-6">
        <h1 className="text-3xl mb-5">Best Before</h1>

        <p>Some Hipster Ipsum:</p>

        <blockquote className="font-serif italic px-6 py-3">
          Flannel pour-over chicharrones food truck iPhone la croix messenger bag slow-carb mukbang
          intelligentsia artisan pop-up authentic celiac air plant. I&apos;m baby kogi neutra health
          goth put a bird on it, distillery man braid actually shabby chic. Fam pork belly kinfolk
          palo santo street art twee iPhone. Iceland normcore retro vibecession. Sustainable retro
          cornhole, ethical man bun twee knausgaard post-ironic edison bulb craft beer polaroid blue
          bottle synth mlkshk. Ennui tonx bespoke cardigan subway tile pop-up pok pok squid.
        </blockquote>
      </main>

      <footer className="p-6 text-xs text-center text-gray-500">Powered by ☕️</footer>
    </div>
  )
}
