import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Best Before</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Best Before</h1>

        <p>Some Hipster Ipsum:</p>

        <p>
          Flannel pour-over chicharrones food truck iPhone la croix messenger bag slow-carb mukbang
          intelligentsia artisan pop-up authentic celiac air plant. I&apos;m baby kogi neutra health
          goth put a bird on it, distillery man braid actually shabby chic. Fam pork belly kinfolk
          palo santo street art twee iPhone. Iceland normcore retro vibecession. Sustainable retro
          cornhole, ethical man bun twee knausgaard post-ironic edison bulb craft beer polaroid blue
          bottle synth mlkshk. Ennui tonx bespoke cardigan subway tile pop-up pok pok squid.
        </p>
      </main>

      <footer>Powered by ☕️</footer>
    </div>
  )
}
